export const dogPuns = [ "Ruff day.",
"Bone Appétit!",
"Dog-gone it.",
"One sick puppy.",
"You’re barking up the wrong tree.",
"Quit hounding me!",
"Howl you doin’?",
"Having a ball!",
"Paws-itively!",
"Oh, paw-lease.",
"Friends fur-ever.",
"Where do dogs go after their tails fall off? The re-tail store.",
"What kind of construction are dogs best at? Roofing.",
"Who is the best dog detective? Sherlock Bones!",
"I almost kicked my dog out, but we renegotiated the terms of his leash.",
"What’s your dog’s favorite Pink Floyd album? Bark Side of the Moon.",
"Who was the dog’s favorite artist? Andy Warhowl.",
"The picnic quickly turned into a Bark-B-Q.",
"The dog is so famous that the pup-arazzi was following him around all day.",
"Have you heard about the new dog movie? It’s called Jurassic Bark.",
"What does a dog like to eat for breakfast? Woofles.",
"He has to constantly call her to check in. She has him on a short leash.",
"I like big mutts and I cannot lie.",
"Luke, I am your paw-ther!",
"Anything is paw-sible.",
"Let’s raise the woof!",
"You’re looking quite fetching today!",
"Where’s the paw-ty at?",
"That dog is so beautiful that she should be on the cover of Vanity Fur.",
"Howl I ever live without you?",
"Just going through a rough pooch lately.",
"I’m mutts about you!",
"I love you, fur real.",
"Trust me, I’m a dog-tor.",
"Remember to put the car in bark.",
"He’s a diamond in the ruff.",
"The fancy dog was quite pawsh.",
"The Dalmatian was hiding because he didn’t want to be spotted.",
"I’m all about that pug life.",
"He’s Great Dane-gerous.",
"My dog’s not fat. He’s just a little husky.",
"You have the corg-key to my heart.",
"When a problem comes along, you must Whippet.",
"What dog does Dracula own? A blood-hound.",
"In this race, the Weiner takes it all.",
"The newest Avenger: Labro-thor.",
"Dachshunds always nap in the shade because they don’t like being hot dogs.",
"I’ll collie you later.",
"My favorite vegetable is collie-flour!",
"He’s doing a thorough Lab report.",
"What do you call a dog magician? A Labracadabrador.",
"“You ain’t nothing but a pound dog.”",
"My dog’s favorite band is The Beagles.",
"My dog hates when it rains because he doesn’t want to step in a poodle.",
"Things happen. No need to terrier-self up about it.",
"Just need a cup of Earl Greyhound tea every day.",
"Happy Howlidays!",
"Merry Christmutts!",
"May your Christmas be furry and bright.",
"Unleashing all kinds of joy this season!",
"Feliz Navi-dog.",
"Dear Santa Paws, I have been a very good boy this year.",
"Santa Paws is comin’ to town.",
"Deck the paws!",
"Oh Christmas treat! Oh Christmas treat!",
"Dachshund through the snow.",
"Santa’s little yelper.",
"Fleas Navidad!",
"Happy Paw-lidays!",
"Looking quite fetching this Christmas." ];